config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :officials
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  get 'welcome/index'

  root 'welcome#index'

  resources :users, only: [:show] do
    collection do
      post :follow_official, action: :follow_official
      post :follow_calendar, action: :follow_calendar
      post :follow_event, action: :follow_event
    end
  end

  resources :officials, only: [:index, :show]

  resources :events

  resources :calendars

end

app/models/official.rb
# == Schema Information
#
# Table name: officials
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  description            :text
#  link                   :string(255)
#  is_company             :boolean
#  like_count             :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  verified               :boolean
#  img_file_name          :string(255)
#  img_content_type       :string(255)
#  img_file_size          :integer
#  img_updated_at         :datetime
#

class Official < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_initialize :default
  validates :name, :description, presence: true

  has_many :calendars, dependent: :destroy
  has_and_belongs_to_many :users, join_table: :users_officials

  has_attached_file :img, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :url => "/assets/officials/:id/:style/:basename.:extension", :path => ":rails_root/public/assets/officials/:id/:style/:basename.:extension"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/

  def default
    self.is_company ||= false
    self.like_count ||= 0
    self.verified ||= false
  end
end

app/controllers/officials_controller.rb
class OfficialsController < ApplicationController
  before_action :set_official, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @officials = Official.all
    respond_with(@officials)
  end

  def show
    @calendars = Calendar.where(official: @official).order(created_at: :desc)
    @events = Event.where(calendar: @calendars).order(created_at: :desc)

    respond_with(@official, @calendars, @events)
  end

  def new
    @official = Official.new
    respond_with(@official)
  end

  def edit
  end

  def create
    @official = Official.new(official_params)
    @official.save
    respond_with(@official)
  end

  def update
    @official.update(official_params)
    respond_with(@official)
  end

  private
    def set_official
      @official = Official.find(params[:id])
    end

    def official_params
      params[:official]
    end
end

app/helpers/officials_helper.rb
module OfficialsHelper
end

app/views/officials/_form.html.erb
<%= simple_form_for(@official) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/officials/edit.html.erb
<h1>Editing official</h1>

<%= render 'form' %>

<%= link_to 'Show', @official %> |
<%= link_to 'Back', officials_path %>

app/views/officials/index.html.erb
<div id="header" class="ui piled segment"><h1>人気公式一覧</h1></div>

<br>

<div id="l-container">
  <%= render "layouts/sidebar"%>
  <div id="s-container">
    <div class="ui segment">
      <div class="ui divided items">
        <% @officials.each do |official| %>
          <div class="item">
            <div class="image">
              <img src="<%=official.img.url(:medium)%>">
            </div>
            <div class="content">
              <a class="header"><%= official.name %></a>
              <div class="meta">
                <span class="cinema"><a href="<%= official.link %>"><%= official.link %></a></span>
              </div>
              <div class="description">
                <p><%= official.description %></p>
              </div>
              <div class="extra">
                <% if official.is_company %>
                  <div class="ui label">会社</div>
                <% end %>
                <%= link_to follow_official_users_path(user: current_user, official: official), :method => :post do %>
                  <div class="ui right floated green button">
                    追加
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/officials/new.html.erb
<h1>New official</h1>

<%= render 'form' %>

<%= link_to 'Back', officials_path %>

app/views/officials/show.html.erb
<div id="header" class="ui piled segment">
  <h1><%=current_official.name%></h1>
  <span>
    <%=link_to destroy_official_session_path, :method => :delete do%>
    <div id="logout-btn" class="ui red animated button">
      <div class="visible content">ログアウト</div>
      <div class="hidden content">Now?</div>
    </div>
    <%end%>
  </span>
</div>

<div id="l-container">
  <%= render "layouts/sidebar"%>
  <div id="s-container">
    <div class="ui tabluar menu">
      <a class="active item" data-tab="cal">
        日程表
      </a>
      <a class="item" data-tab="event">
        イベント
      </a>
      <a class="item" data-tab="actions">
        動作
      </a>
      <a class="item" data-tab="da">
        データ分析
      </a>
    </div>
      <div class="ui bottom attached active tab segment" data-tab="cal">
        <!-- Load Calendars -->
        <div class="ui cards">
          <% @calendars.each do |calendar| %>
          <div class="card">
            <div class="image">
              <% if calendar.img? %>
              <% img_link = calendar.img.url(:medium) %>
              <% else %>
                <% img_link = "/default/1.jpg" %>
              <% end %>
              <img src="<%= img_link %>">
            </div>
            <div class="content">
              <div class="header"><%= calendar.name %></div>
              <div class="meta">
                <%=link_to "#{calendar.official.name}", official_path(calendar.official)%>
              </div>
              <div class="description">
                <%= calendar.description %>
              </div>
            </div>
            <div class="extra content">
              <span class="right floated">
                <% if calendar.official.is_company? %>
                  <i class="fa-star icon"></i>
                  公式確認
                <% else %>
                  開放
                <% end %>
              </span>
              <span>
                <i class="heart icon"></i>
                 <%= calendar.like_count %>
              </span>
            </div>
            <%=link_to edit_calendar_path(calendar) do %>
              <div class="ui bottom attached button">
                <i class="pencil icon"></i>
                編集
              </div>
            <% end %>
            <%=link_to calendar_path(calendar), :method => :delete, :confirm => "Are you sure to delete?" do %>
              <div class="ui bottom attached button">
                <i class="trash icon"></i>
                削除
              </div>
            <% end %>
          </div>
          <% end %>
        </div>
        <!-- load calendar cards -->
      </div>

      <div class="ui bottom attached tab segment" data-tab="event">
        <!-- Load Events Data -->
        <div class="ui cards">
          <% @events.each do |event| %>
          <div class="ui card">
            <div class="content">
              <%=link_to edit_event_path(event) do%>
                <i class="right floated pencil icon"></i>
              <% end %>
              <%=link_to event_path(event), :method => :delete, :confirm => "Are you sure to delete?" do%>
                <i class="right floated trash icon"></i>
              <% end %>
              <div class="header"><%= event.name %></div>
              <div class="description">
                <p><%= event.description %></p>
              </div>
            </div>
            <div class="extra content">
              <span class="left floated like">
                <i class="like icon"></i>
                <%= event.like_count %>
              </span>
              <span class="right floated">
                "Add Later"
              </span>
            </div>
            <div class="extra content">
              <% if event.is_all_day %>
              <span class="left floated">
                <%= event.start_time.to_formatted_s(:short) %>
              </span>
              <span class="right floated">
                一日
              </span>
              <% else %>
              <span class="left floated">
                <%= event.start_time.to_formatted_s(:short) %>
              </span>
              <span class="right floated">
                <%= event.end_time.to_formatted_s(:short) %>
              </span>
              <% end %>
            </div>
            </div>
          <% end %>
        </div>
        <!-- Load Events Data -->
      </div>

      <div class="ui bottom attached tab segment" data-tab="actions">
        <%=link_to new_calendar_path do%>
          <div class="ui pink button">新日程表追加</div>
        <% end %>
        <%=link_to new_event_path do%>
          <div class="ui teal button">新イベント追加</div>
        <% end %>
      </div>

      <div class="ui bottom attached tab segment" data-tab="da">
        Data Analysis
      </div>

  </div>
</div>