config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :officials
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  get 'welcome/index'

  root 'welcome#index'

  resources :users, only: [:show] do
    collection do
      post :follow_official, action: :follow_official
      post :follow_calendar, action: :follow_calendar
      post :follow_event, action: :follow_event
    end
  end

  resources :officials, only: [:index, :show]

  resources :events

  resources :calendars

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  description      :text
#  place            :string(255)
#  is_all_day       :boolean
#  start_time       :datetime
#  end_time         :datetime
#  link             :string(255)
#  note             :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  calendar_id      :integer
#  like_count       :integer
#  img_file_name    :string(255)
#  img_content_type :string(255)
#  img_file_size    :integer
#  img_updated_at   :datetime
#

class Event < ActiveRecord::Base
  after_initialize :default

  validates :name, :description, presence: true

  belongs_to :calendar
  has_and_belongs_to_many :users, join_table: :users_events

  has_attached_file :img, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :url => "/assets/events/:id/:style/:basename.:extension", :path => ":rails_root/public/assets/events/:id/:style/:basename.:extension"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/

  def default
    self.is_all_day ||= false
    self.like_count ||= 0
    self.start_time ||= Time.now
    self.end_time ||= self.start_time + 1.hour
  end

  def as_json(options = {})
    {
      :id => self.id,
      :title => self.name,
      :start => self.start_time,
      :end => self.end_time,
      :description => self.description,
      :allDay => self.is_all_day,
      :location => self.place,
      :like_count => self.like_count,
  }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_official!, only: [:new, :edit, :create, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all.order(like_count: :desc)
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
    respond_with(@event)
  end

  def update
    @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:calendar_id, :name, :description, :place, :link, :note, :is_all_day, :start_time, :end_time, :img, :is_public)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<div class="ui center aligned stacked segment">
  <div id="formbox" class="ui left aligned segment">

  <%= simple_form_for(@event) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%=f.input :calendar_id, :collection => current_official.calendars, :label_method => :name, :value_method => :id, :include_blank => true %>
      <%=f.input :name %>
      <%=f.input :description, :as => :text %>
      <%=f.input :img, as: :file, hint: "Img should be bigger than 300x300" %>
      <%=f.input :place %>
      <%=f.input :link %>
      <%=f.input :note, :as => :text %>
      <%=f.input :is_all_day, :as => :boolean %>
      <%=f.input :start_time, :as => :datetime %>
      <%=f.input :end_time, :as => :datetime %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="ui piled segment"><h1>人気イベント一覧</h1></div>

<br>

<div id="l-container">
  <%= render "layouts/sidebar"%>
  <div id="s-container">
    <div class="ui special cards">
      <% @events.each do |event| %>
      <div class="card">
        <div class="dimmable image">
          <% if event.img? %>
            <% img_link = event.img.url %>
          <% else %>
            <% img_link = "/default/1.jpg" %>
          <% end %>
          <% if current_user %>
          <div class="ui dimmer">
            <div class="content">
              <div class="center">
                <%=link_to follow_event_users_path(user: current_user, event: event), :method => :post do%>
                  <% if current_user.events.include? event %>
                    <div class="ui inverted button">削除</div>
                  <% elsif %>
                    <div class="ui inverted button">追加</div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <% end %>
          <img src="<%= img_link%>">
        </div>
        <div class="content">
          <div class="header"><%= event.name %></div>
          <div class="meta">
            <%=link_to "#{event.calendar.name}", official_path(event.calendar)%>
          </div>
          <div class="description">
            <%= event.description %>
          </div>
        </div>
        <div class="extra content">
          <span class="right floated">
            <%= event.start_time.to_date %>
          </span>
          <span>
            <i class="heart icon"></i>
             <%= event.like_count %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>