config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :officials
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations"}

  get 'welcome/index'

  root 'welcome#index'

  resources :users, only: [:show] do
    collection do
      post :follow_official, action: :follow_official
      post :follow_calendar, action: :follow_calendar
      post :follow_event, action: :follow_event
    end
  end

  resources :officials, only: [:index, :show]

  resources :events

  resources :calendars

end

app/models/calendar.rb
# == Schema Information
#
# Table name: calendars
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  description      :text
#  link             :string(255)
#  like_count       :integer
#  is_public        :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  official_id      :integer
#  img_file_name    :string(255)
#  img_content_type :string(255)
#  img_file_size    :integer
#  img_updated_at   :datetime
#

class Calendar < ActiveRecord::Base
  after_initialize :default

  validates :name, :description, presence: true

  has_many :events, dependent: :destroy
  belongs_to :official
  has_and_belongs_to_many :users, join_table: :users_calendars

  has_attached_file :img, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :url => "/calendars/:id/:style/:basename.:extension", :path => ":rails_root/public/calendars/:id/:style/:basename.:extension"
  validates_attachment_content_type :img, :content_type => /\Aimage\/.*\Z/

  def default
    self.like_count ||= 0
    self.is_public ||= true
  end

end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_official!, only: [:new, :edit, :create, :update, :destroy]

  respond_to :html

  def index
    @calendars = Calendar.all.order(like_count: :desc).take(10)
    respond_with(@calendars)
  end

  def show
    respond_with(@calendar)
  end

  def new
    @calendar = Calendar.new
    respond_with(@calendar)
  end

  def edit
  end

  def create
    @calendar = Calendar.new(calendar_params)
    @calendar.official = current_official
    @calendar.save
    respond_with(@calendar)
  end

  def update
    @calendar.update(calendar_params)
    respond_with(@calendar)
  end

  def destroy
    @calendar.destroy
    respond_with(@calendar)
  end

  private
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    def calendar_params
      params.require(:calendar).permit(:name, :decription, :img, :link, :is_public)
    end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/views/calendars/_form.html.erb
<div class="ui center aligned stacked segment">
  <div id="formbox" class="ui left aligned segment">

  <%= simple_form_for(@calendar) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :description, :as => :text%>
      <%= f.input :is_public, :as => :boolean %>
      <%= f.input :img, as: :file, hint: "Img should be bigger than 300x300" %>
      <%= f.input :link %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>

  </div>
</div>

app/views/calendars/edit.html.erb
<h1>Editing calendar</h1>

<%= render 'form' %>

<%= link_to 'Show', @calendar %> |
<%= link_to 'Back', calendars_path %>

app/views/calendars/index.html.erb
<div id="header" class="ui piled segment"><h1>人気日程表一覧</h1></div>

<br>
<div id="l-container">
  <%= render "layouts/sidebar"%>
  <div id="s-container">
    <div class="ui special cards">
      <% @calendars.each do |calendar| %>
      <div class="card">
        <div class="dimmable image">
          <% if calendar.img? %>
            <% img_link = calendar.img.url(:medium) %>
          <% else %>
            <% img_link = "/default/1.jpg" %>
          <% end %>
          <% if current_user %>
            <div class="ui dimmer">
              <div class="content">
                <div class="center">
                  <%=link_to follow_calendar_users_path(user: current_user, calendar: calendar), :method => :post do%>
                  <% if current_user.calendars.include? calendar %>
                      <div class="ui inverted button">削除</div>
                    <% elsif %>
                      <div class="ui inverted button">追加</div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
          <img src="<%= img_link%>">
        </div>
        <div class="content">
          <div class="header"><%= calendar.name %></div>
          <div class="meta">
            <%=link_to "#{calendar.official.name}", official_path(calendar.official)%>
          </div>
          <div class="description">
            <%= calendar.description %>
          </div>
        </div>
        <div class="extra content">
          <span class="right floated">
            <% if calendar.official.is_company? %>
              <i class="fa-star icon"></i>
              公式確認
            <% else %>
              開放
            <% end %>
          </span>
          <span>
            <i class="heart icon"></i>
             <%= calendar.like_count %>
          </span>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/calendars/new.html.erb
<h1>New calendar</h1>

<%= render 'form' %>

<%= link_to 'Back', calendars_path %>

app/views/calendars/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_calendar_path(@calendar) %> |
<%= link_to 'Back', calendars_path %>